<a href="https://colab.research.google.com/github/ghadayoussef/AndroidTutorialForBeginners/blob/master/Copy_of_ANN_ppg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import keras
from tensorflow.keras.models import Sequential
from keras.preprocessing.image import ImageDataGenerator
import numpy as np 
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D,Flatten,Dense,Activation,Dropout,MaxPooling2D
from keras.activations import relu
from keras.optimizers import Adam
from keras.models import Model
import os
from sklearn.model_selection import StratifiedKFold

Using TensorFlow backend.


In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
import numpy as np
from os import listdir
import cv2
from PIL import Image as I
from numpy import *
#image = cv2.imread('/content/drive/My Drive/heart_rate/false_images/a103l.png')
#print("here",image)
def load_files():
    """
        Load each name file in the directory
        :param directory:
        :return:
    """
    path_f= '/content/drive/My Drive/heart_rate/false_images/'
    path_t = '/content/drive/My Drive/heart_rate/true_images/'
    train = []
    validation = []
    test = []
    #n -> 0
    #a -> 1
    #b -> 2
    #f -> 3
    #t -> 4
    #v -> 5
    classes = {0,1, 2, 3, 4,5}

    classes_dict = dict()

    for key in classes:
        classes_dict[key] = [f for f in listdir(path_f) if key == f[0]]
        #random.shuffle(classes_dict[key])
    
    classes_dict[0] = [f for f in listdir(path_t)]
    Images=[]
    Labels=[]
    #print(classes_dict.get('a'))
    print(len(classes_dict))
    #i=0
    #for key in classes_dict:
    #  images[i]=classes_dict.get(key)
    #  i+=1
    #print("\n images \n ",images[0],"\n\n")
    #
    imagea=[]
    imageb=[]
    imagef=[]
    imaget=[]
    imagev=[]
    imagen=[]
    
    
    for filename in listdir(path_t):       
      image = cv2.imread(path_t+filename)
      #image = array(I.open(path_t+filename).convert('L'))
      #image=np.invert(image)
      Image = cv2.resize(image, (100,100))
      Image = cv2.cvtColor(Image, cv2.COLOR_BGR2GRAY)     
      #Image = np.expand_dims(Image, axis=2)
      #Image = Image.astype('float32')
      
      Image[:] = [x / 255 for x in Image]
      
      #Image /=255
      Images.append(Image)
      if filename[0]=='a':
        Labels.append(1) 
        imagea.append(Image)
      if filename[0]=='b':
        Labels.append(2) 
        imageb.append(Image)
      if filename[0]=='f':
        Labels.append(3)
        imagef.append(Image)
      if filename[0]=='t':
        Labels.append(4)
        imaget.append(Image)
      if filename[0]=='v':
        Labels.append(5)
        imagev.append(Image)
    
    
    
    for filename in listdir(path_f):       
      #image = array(I.open(path_t+filename).convert('L'))
      #image=np.invert(image)
      image = cv2.imread(path_f+filename)
      Image = cv2.resize(image, (100,100))
      Image = cv2.cvtColor(Image, cv2.COLOR_BGR2GRAY)
      #Image = np.expand_dims(Image, axis=2)
      #Image = Image.astype('float32')
      #Image /=255
      Image[:] = [x / 255 for x in Image]
      Images.append(Image) 
      imagen.append(Image)
      Labels.append(0)
    #print("Images \n",Images[0],"\n")
    print("typpeeeeeeeeeeeeee of Imageeeeee ",type(Images[0]))
    print("Labels \n",Labels,"\n","len labels",len(Labels),"\n")
    print("len images",len(Images))
    print("len image A",len(imagea))#,"\n","image A",imagea,"\n")
    print("len image B",len(imageb))#,"\n","image B",imageb,"\n")
    print("len image F",len(imagef))#,"\n","image F",imagef,"\n")
    print("len image T",len(imaget))#,"\n","image T",imaget,"\n")
    print("len image V",len(imagev))#,"\n","image V",imagev,"\n")
    print("len image N",len(imagen))#,"\n","image N",imagen,"\n")
    print(len(Images))
    
    #return classes_dict
    return Images,Labels,imagea,imageb,imagef,imaget,imagev,imagen
    
print(load_files())

6
typpeeeeeeeeeeeeee of Imageeeeee  <class 'numpy.ndarray'>
Labels 
 [5, 4, 5, 2, 5, 4, 3, 5, 2, 4, 3, 2, 3, 4, 2, 3, 1, 1, 5, 5, 4, 5, 4, 5, 2, 4, 4, 4, 2, 2, 5, 4, 4, 5, 4, 4, 1, 5, 4, 2, 4, 4, 1, 4, 3, 4, 4, 2, 2, 4, 4, 5, 5, 1, 4, 4, 2, 4, 2, 4, 4, 4, 2, 4, 5, 5, 4, 5, 4, 4, 2, 4, 4, 5, 4, 4, 4, 5, 5, 4, 4, 4, 4, 5, 4, 4, 4, 5, 1, 2, 4, 5, 4, 4, 5, 5, 4, 5, 1, 4, 4, 5, 4, 1, 2, 5, 4, 4, 5, 4, 2, 1, 4, 5, 4, 4, 5, 4, 4, 5, 1, 4, 2, 4, 4, 4, 4, 4, 4, 1, 1, 2, 5, 4, 4, 4, 4, 5, 5, 4, 5, 5, 1, 5, 5, 3, 5, 4, 2, 5, 4, 4, 5, 4, 2, 4, 5, 5, 4, 5, 1, 5, 2, 5, 4, 5, 4, 2, 4, 4, 4, 1, 5, 4, 2, 4, 1, 4, 4, 2, 4, 4, 2, 4, 4, 2, 5, 2, 2, 2, 2, 5, 4, 5, 5, 4, 5, 4, 5, 5, 4, 5, 1, 2, 2, 2, 4, 5, 4, 4, 5, 2, 2, 4, 4, 5, 4, 2, 5, 4, 4, 2, 5, 2, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [4]:
Images,Labels,imagea,imageb,imagef,imaget,imagev,imagen =load_files()
Images = np.asarray(Images)
Labels = np.asarray(Labels)
print(Images.shape[1:])

6
typpeeeeeeeeeeeeee of Imageeeeee  <class 'numpy.ndarray'>
Labels 
 [5, 4, 5, 2, 5, 4, 3, 5, 2, 4, 3, 2, 3, 4, 2, 3, 1, 1, 5, 5, 4, 5, 4, 5, 2, 4, 4, 4, 2, 2, 5, 4, 4, 5, 4, 4, 1, 5, 4, 2, 4, 4, 1, 4, 3, 4, 4, 2, 2, 4, 4, 5, 5, 1, 4, 4, 2, 4, 2, 4, 4, 4, 2, 4, 5, 5, 4, 5, 4, 4, 2, 4, 4, 5, 4, 4, 4, 5, 5, 4, 4, 4, 4, 5, 4, 4, 4, 5, 1, 2, 4, 5, 4, 4, 5, 5, 4, 5, 1, 4, 4, 5, 4, 1, 2, 5, 4, 4, 5, 4, 2, 1, 4, 5, 4, 4, 5, 4, 4, 5, 1, 4, 2, 4, 4, 4, 4, 4, 4, 1, 1, 2, 5, 4, 4, 4, 4, 5, 5, 4, 5, 5, 1, 5, 5, 3, 5, 4, 2, 5, 4, 4, 5, 4, 2, 4, 5, 5, 4, 5, 1, 5, 2, 5, 4, 5, 4, 2, 4, 4, 4, 1, 5, 4, 2, 4, 1, 4, 4, 2, 4, 4, 2, 4, 4, 2, 5, 2, 2, 2, 2, 5, 4, 5, 5, 4, 5, 4, 5, 5, 4, 5, 1, 2, 2, 2, 4, 5, 4, 4, 5, 2, 2, 4, 4, 5, 4, 2, 5, 4, 4, 2, 5, 2, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [0]:
#lessa msh sha3'ala
#save the Images and Labels array instead of loading images into array every run
import pickle
pickle_out=open("Images.pickle","wb")
pickle.dump(Images,pickle_out)
pickle_out.close
pickle_out=open("Labels.pickle","wb")
pickle.dump(Labels,pickle_out)
pickle_out.close

<function BufferedWriter.close>

In [0]:
#lessa msh sha3'ala
pickle_in=open("Images.pickle","rb")
Images=pickle.load(pickle_in)
pickle_in=open("Labels.pickle","rb")
Labels=pickle.load(pickle_in)

In [0]:
import glob
import numpy as np
import os
from re import findall
import matplotlib.image as mpimg 
import matplotlib.pyplot as plt 
from skimage import color
import cv2
import pandas as pd
import keras 
from keras_preprocessing import image


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Images, Labels, test_size=0.2)
#X_train=Images
#Y_train=Labels
#from sklearn.utils import shuffle
#X_train,Y_train=shuffle(Images,Labeks,random_state=4)
#print("X_train \n",X_train,"\n")
print("Y_train \n",Y_train,"\n")
#print("X_test \n",X_test,"\n")
print("Y_test \n",Y_test,"\n")
print(len(X_train))
print(len(X_test))
print(len(Y_train))


Y_train 
 [0 0 0 4 0 0 0 0 0 0 4 0 2 0 0 0 1 5 5 0 0 4 0 1 0 3 4 0 0 2 0 0 0 0 4 0 4
 0 2 0 0 0 0 0 5 2 3 0 0 0 0 5 0 0 5 0 0 4 0 4 0 0 5 0 0 4 0 0 0 0 2 0 0 0
 0 4 2 3 0 0 0 0 5 0 2 0 5 0 0 5 0 0 0 4 0 0 4 5 0 0 0 2 5 4 0 4 1 0 0 0 0
 5 0 0 0 4 0 4 0 0 0 0 0 0 0 0 0 0 4 4 0 4 0 0 0 0 4 0 5 4 0 0 4 3 5 0 4 0
 0 0 0 0 0 0 1 0 0 0 4 0 0 0 1 2 4 0 0 2 2 0 4 0 0 5 0 0 0 4 0 0 0 5 0 4 0
 0 0 0 5 0 0 0 0 0 0 0 0 0 2 4 0 0 0 0 0 5 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 5
 2 0 0 4 5 0 0 0 0 5 0 5 0 0 2 4 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 4 0 4
 2 0 0 0 0 0 5 5 0 0 0 0 0 0 2 0 4 0 2 0 0 0 5 0 0 4 0 0 0 0 5 1 0 5 4 0 0
 0 0 4 0 5 4 0 5 0 4 4 1 4 0 0 0 0 4 1 5 4 0 4 4 0 0 0 0 0 4 4 0 0 5 0 5 0
 0 5 0 0 0 0 0 0 5 0 2 4 0 0 0 4 2 2 0 0 5 0 0 4 0 0 0 1 0 4 0 0 0 0 4 4 0
 4 0 0 4 4 0 0 5 4 0 4 0 4 4 0 2 5 0 4 4 0 1 0 0 5 0 4 1 0 0 4 0 4 0 0 4 5
 0 5 2 4 0 0 4 4 5 0 0 0 4 4 3 0 5 0 0 0 0 0 0 0 0 0 0 5 0 5 0 0 5 4 0 0 4
 0 0 2 4 0 0 0 0 0 5 0 0 5 0 2 0 0 4 4 0 4 0 0 4 2 4 0 4 0 0 0 2 0 0 4 0 5
 4 0 0 5 0 4 5 

In [0]:
print(X_train.shape[2])

100


In [0]:
x_train=[]
for i in range(len(X_train)):
  x_train.append(X_train[i].flatten())
print(len(x_train))
#x_val=[]
#for i in range(len(X_val)):
#  x_val.append(X_val[i].flatten())
#print(len(x_val))

501


In [0]:
x_test=[]
for i in range(len(X_test)):
  x_test.append(X_test[i].flatten())
print(len(x_test))

126


In [0]:
x=np.asarray(x_train)
print(x.shape[1:])
y=np.asarray(Y_train)
print(len(y))

(10000,)
501


In [0]:
xtest=np.asarray(x_test)
print(xtest.shape[1:])
ytest=np.asarray(Y_test)
print(len(ytest))

(10000,)
126


In [36]:
height=100
width=100
dims=1
shape=x.shape[1:]
print(shape)
def create_model(x):
    model = Sequential()
    
    model.add(Dense(1,input_shape=x.shape[1:], activation='relu'))
    #model.add(Dense(1, input_dim=x,input_sdim=height,width,dims, activation='relu'))
    model.add(Dense(1, activation='softmax'))
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

    return model
model=create_model(x)
model.fit(x,y, batch_size=32, epochs=10)# validation_split=0.1)
  

(10000,)
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
748/748 [==============================] - 0s 582us/sample - loss: 3.9037 - acc: 0.1083
Epoch 2/10
748/748 [==============================] - 0s 98us/sample - loss: 3.9037 - acc: 0.1083
Epoch 3/10
748/748 [==============================] - 0s 91us/sample - loss: 3.9037 - acc: 0.1083
Epoch 4/10
748/748 [==============================] - 0s 87us/sample - loss: 3.9037 - acc: 0.1083
Epoch 5/10
748/748 [==============================] - 0s 88us/sample - loss: 3.9037 - acc: 0.1083
Epoch 6/10
748/748 [==============================] - 0s 84us/sample - loss: 3.9037 - acc: 0.1083
Epoch 7/10
748/748 [==============================] - 0s 92us/sample - loss: 3.9037 - acc: 0.1083
Epoch 8/10
748/748 [==============================] - 0s 99us/sample - loss: 3.9037 - acc: 0.1083
Epoch 9/10
748/748 [==============================] - 0s 59us/sample - loss: 3.9037 - acc: 0.1083
Epoch 10/10


In [35]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

def CNN_model(X_train):
  model = Sequential()

  model.add(Conv2D(256, (3, 3), input_shape=X_train.shape[0:]))
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(2, 2)))
  
  model.add(Conv2D(256, (3, 3)))
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(2, 2)))
  
  model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
  
  model.add(Dense(64))
  
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  
  model.compile(loss='sparse_categorical_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])
  return model
model=CNN_model(xtrain_unflattened)  
model.fit(xtrain_unflattened, ytrain_unflattened, batch_size=32, epochs=10, validation_split=0.1)

#print(X_train.shape[0:])

TypeError: ignored

In [38]:
#model = create_model()
from sklearn import svm
from sklearn.metrics import accuracy_score
#clf = svm.SVC(kernel='linear', C = 1.0)
clf=svm.SVC(kernel='rbf',gamma=0.1,C=10)
clf.fit(x,y)
print(clf.predict(xtest))
print(ytest)
#data = (x_train ,Y_train)
#model.fit_generator((x_train ,Y_train), epochs = 10,steps_per_epoch=1 )#validation_data=(x_val,Y_val))
#data_train = datagen.flow(x=X_train, y=Y_train, batch_size=32, shuffle=True)
    
#results = model.fit_generator(data_train,steps_per_epoch=data_train.n/32 ,verbose=1,epochs=1)#validation_data=data_val) 
#model.fit(X_train,Y_train)
#clf.score(x, xtest)
predicted = clf.predict(xtest)

# get the accuracy
print(accuracy_score(ytest, predicted))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0
 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 4 0 0 4 0 0 0 0 4 0 0 4 0 4 0 0 0 0 0 0 4 0 2 2 0 0 0 4 0 0 0 0 4 0 0 0
 0 0 0 0 0 0 2 0 0 4 0 0 5 0 5 5 2 5 4 5 5 2 5 5 0 0 4 0 4 0 0 0 0 0 0 5 0
 0 0 0 4 0 0 5 3 0 0 0 0 0 2 0 4 0 5 2 4 0 0 0 0 5 0 0 0 0 0 0 0 0 2 4 0 5
 0 5 0 0 0 4 5 0 4 0 4 0 0 0 0]
0.6507936507936508


In [0]:
#import numpy as np
#import matplotlib.pyplot as plt
#def plotSVC(title):
#  # create a mesh to plot in
#  x_min, x_max = X[:, 0].min() — 1, X[:, 0].max() + 1
#  y_min, y_max = X[:, 1].min() — 1, X[:, 1].max() + 1
#  h = (x_max / x_min)/100
#  xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
#  np.arange(y_min, y_max, h))
#
#  plt.subplot(1, 1, 1)
#  Z = svc.predict(np.c_[xx.ravel(), yy.ravel()])
#  Z = Z.reshape(xx.shape)
#  plt.contourf(xx, yy, Z, cmap=plt.cm.Paired, alpha=0.8)
#
#  plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.Paired)
#  plt.xlabel(‘Sepal length’)
#  plt.xlim(xx.min(), xx.max())
#  plt.title(title)
#  plt.show()

# **tuning  of SVC**

In [0]:
gammas = [0.1, 1, 10, 100]
kernels = ['linear', 'rbf', 'poly']
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
for g in gammas:
  for k in kernels:
    svc = svm.SVC(kernel=k,gamma=g).fit(x, y)    
    predicted = svc.predict(xtest)  
    results = confusion_matrix(ytest, predicted)
    print ('Confusion Matrix :')
    print(results)
    print ('Accuracy Score :',accuracy_score(ytest, predicted))
    print ('Report : ')
    print (classification_report(ytest, predicted))
    print(results)
    #score = svc.evaluate(x,y)
    #print('Test loss:', score[0])
    #print('Test accuracy:', score[1]) 
    #y_pred =np.round( model.predict(X_test))
    #print(confusion_matrix(yest,y_pred))   
    #print(accuracy_score(Y_test, y_pred)) 
    #plotSVC(‘kernel=’ + str(kernel))
    #plotSVC("gamma" , str(g))
    #predicted = clf.predict(xtest)

Confusion Matrix :
[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]
Accuracy Score : 0.6031746031746031
Report : 
              precision    recall  f1-score   support

           0       0.69      0.84      0.76        83
           2       0.50      0.12      0.20         8
           3       0.00      0.00      0.00         1
           4       0.24      0.21      0.22        19
           5       0.20      0.07      0.10        15

   micro avg       0.60      0.60      0.60       126
   macro avg       0.32      0.25      0.26       126
weighted avg       0.54      0.60      0.56       126

[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]
Accuracy Score : 0.6507936507936508
Report : 
              precision    recall  f1-score   support

           0       0.66      0.98      0.79        83
           2       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1
           4       0.33      0.05      0.09        19
           5       0.00      0.00      0.00        15

   micro avg       0.65      0.65      0.65       126
   macro avg       0.20      0.21      0.18       126
weighted avg       0.48      0.65      0.53       126

[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[74  1  0  6  2]
 [ 5  0  0  2  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]
Accuracy Score : 0.626984126984127
Report : 
              precision    recall  f1-score   support

           0       0.70      0.89      0.78        83
           2       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1
           4       0.29      0.21      0.24        19
           5       0.20      0.07      0.10        15

   micro avg       0.63      0.63      0.63       126
   macro avg       0.24      0.23      0.23       126
weighted avg       0.53      0.63      0.56       126

[[74  1  0  6  2]
 [ 5  0  0  2  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]
Accuracy Score : 0.6031746031746031
Report : 
              precision    recall  f1-score   support

           0       0.69      0.84      0.76        83
           2       0.50      0.12      0.20         8
           3       0.00      0.00      0.00         1
           4       0.24      0.21      0.22        19
           5       0.20      0.07      0.10        15

   micro avg       0.60      0.60      0.60       126
   macro avg       0.32      0.25      0.26       126
weighted avg       0.54      0.60      0.56       126

[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]
Accuracy Score : 0.6507936507936508
Report : 
              precision    recall  f1-score   support

           0       0.66      0.98      0.79        83
           2       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1
           4       0.33      0.05      0.09        19
           5       0.00      0.00      0.00        15

   micro avg       0.65      0.65      0.65       126
   macro avg       0.20      0.21      0.18       126
weighted avg       0.48      0.65      0.53       126

[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[74  1  0  6  2]
 [ 5  0  0  2  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]
Accuracy Score : 0.626984126984127
Report : 
              precision    recall  f1-score   support

           0       0.70      0.89      0.78        83
           2       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1
           4       0.29      0.21      0.24        19
           5       0.20      0.07      0.10        15

   micro avg       0.63      0.63      0.63       126
   macro avg       0.24      0.23      0.23       126
weighted avg       0.53      0.63      0.56       126

[[74  1  0  6  2]
 [ 5  0  0  2  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]
Accuracy Score : 0.6031746031746031
Report : 
              precision    recall  f1-score   support

           0       0.69      0.84      0.76        83
           2       0.50      0.12      0.20         8
           3       0.00      0.00      0.00         1
           4       0.24      0.21      0.22        19
           5       0.20      0.07      0.10        15

   micro avg       0.60      0.60      0.60       126
   macro avg       0.32      0.25      0.26       126
weighted avg       0.54      0.60      0.56       126

[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]
Accuracy Score : 0.6507936507936508
Report : 
              precision    recall  f1-score   support

           0       0.66      0.98      0.79        83
           2       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1
           4       0.33      0.05      0.09        19
           5       0.00      0.00      0.00        15

   micro avg       0.65      0.65      0.65       126
   macro avg       0.20      0.21      0.18       126
weighted avg       0.48      0.65      0.53       126

[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[68  1  0 13  1]
 [ 6  0  0  2  0]
 [ 1  0  0  0  0]
 [14  0  0  5  0]
 [12  0  0  2  1]]
Accuracy Score : 0.5873015873015873
Report : 
              precision    recall  f1-score   support

           0       0.67      0.82      0.74        83
           2       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1
           4       0.23      0.26      0.24        19
           5       0.50      0.07      0.12        15

   micro avg       0.59      0.59      0.59       126
   macro avg       0.28      0.23      0.22       126
weighted avg       0.54      0.59      0.54       126

[[68  1  0 13  1]
 [ 6  0  0  2  0]
 [ 1  0  0  0  0]
 [14  0  0  5  0]
 [12  0  0  2  1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]
Accuracy Score : 0.6031746031746031
Report : 
              precision    recall  f1-score   support

           0       0.69      0.84      0.76        83
           2       0.50      0.12      0.20         8
           3       0.00      0.00      0.00         1
           4       0.24      0.21      0.22        19
           5       0.20      0.07      0.10        15

   micro avg       0.60      0.60      0.60       126
   macro avg       0.32      0.25      0.26       126
weighted avg       0.54      0.60      0.56       126

[[70  1  0 10  2]
 [ 5  1  0  1  1]
 [ 1  0  0  0  0]
 [14  0  0  4  1]
 [12  0  0  2  1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion Matrix :
[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]
Accuracy Score : 0.6507936507936508
Report : 
              precision    recall  f1-score   support

           0       0.66      0.98      0.79        83
           2       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1
           4       0.33      0.05      0.09        19
           5       0.00      0.00      0.00        15

   micro avg       0.65      0.65      0.65       126
   macro avg       0.20      0.21      0.18       126
weighted avg       0.48      0.65      0.53       126

[[81  0  0  2  0]
 [ 8  0  0  0  0]
 [ 1  0  0  0  0]
 [18  0  0  1  0]
 [15  0  0  0  0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# **UpSampling**

In [31]:
from sklearn.utils import resample
import pandas as pd
import numpy as np
df_minority_upsampled_v = resample(imagev,replace=True,n_samples=47,random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_v = np.vstack([imagev, df_minority_upsampled_v])

df_minority_upsampled_a = resample(imagea,replace=True,n_samples=91,random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_a = np.vstack([imagea, df_minority_upsampled_a])

df_minority_upsampled_b = resample(imageb,replace=True,n_samples=69,random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_b = np.vstack([imageb, df_minority_upsampled_b])

df_minority_upsampled_f = resample(imagef,replace=True,n_samples=102,random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_f = np.vstack([imagef, df_minority_upsampled_f])


#df_minority_upsampled_t = resample(imaget,replace=True,n_samples=226,random_state=123)
# 
## Combine majority class with upsampled minority class
#df_upsampled_t = np.vstack([imaget, df_minority_upsampled_t])

 
# Display new class counts
#df_upsampled_v.balance.value_counts()
#print(type(df_minority_upsampled_v))
print("v upsampled",len(df_upsampled_v))
print(len(df_minority_upsampled_v))
print(len(imagev))
#print(df_upsampled_v)
print(type(df_minority_upsampled_a))
print("a upsampled",len(df_upsampled_a))
print(len(df_minority_upsampled_a))
print(len(imagea))
#print(df_upsampled_a)
print(type(df_minority_upsampled_b))
print("b upsampled",len(df_upsampled_b))
print(len(df_minority_upsampled_b))
print(len(imageb))
print(type(df_minority_upsampled_f))
print("f upsampled",len(df_upsampled_f))
print(len(df_minority_upsampled_f))
print(len(imagef))
#print(type(df_minority_upsampled_t))
#print(len(df_upsampled_t))
#print(len(df_minority_upsampled_t))
#print(len(imaget))

v upsampled 108
47
61
<class 'list'>
a upsampled 108
91
17
<class 'list'>
b upsampled 108
69
39
<class 'list'>
f upsampled 108
102
6


In [14]:
n=np.full(396, 0)
a=np.full((108), 1)
b=np.full((108), 2)
f=np.full((108), 3)
t=np.full((108), 4)
v=np.full((108), 5)
upsampled_labels=[]
upsampled_labels.append(n)
upsampled_labels.append(a)
upsampled_labels.append(b)
upsampled_labels.append(f)
upsampled_labels.append(t)
upsampled_labels.append(v)
item=0
flat_labels=[]
for i in range(len(upsampled_labels)):
  for j in range(len(upsampled_labels[i])):
    flat_labels.append(upsampled_labels[i][j])
    #print(j)
    
print(flat_labels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [32]:
upsampled_images=[]
upsampled_images.append(imagen)
upsampled_images.append(df_upsampled_a)
upsampled_images.append(df_upsampled_b)
upsampled_images.append(df_upsampled_f)
upsampled_images.append(imaget)
upsampled_images.append(df_upsampled_v)

#print(len(upsampled_images[5]))
flat_upsampled=[]                           
for i in range(len(upsampled_images)):
  for j in range(len(upsampled_images[i])):
    flat_upsampled.append(upsampled_images[i][j])
print(flat_upsampled)


[array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8), array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8), array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8), array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8), array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1

In [33]:
from sklearn.model_selection import train_test_split
from numpy import array
X_train, X_test, Y_train, Y_test = train_test_split(flat_upsampled,flat_labels, test_size=0.2)
#X_train=Images
#Y_train=Labels
#from sklearn.utils import shuffle
#X_train,Y_train=shuffle(Images,Labeks,random_state=4)
#print("X_train \n",X_train,"\n")
print("Y_train \n",Y_train,"\n")
#print("X_test \n",X_test,"\n")
print("Y_test \n",Y_test,"\n")
print(len(X_train))
print(len(X_test))
print(len(Y_train))
x_train=[]
for i in range(len(X_train)):
  x_train.append(X_train[i].flatten())
print("len x_train",len(x_train),"\n")


x_test=[]
for i in range(len(X_test)):
  x_test.append(X_test[i].flatten())
print("len x_test",len(x_test),"\n")

x=np.asarray(x_train)
#print(x.shape[1:])
y=np.asarray(Y_train)
xtest=np.asarray(x_test)
ytest=np.asarray(Y_test)
#print(len(y))
xtrain_unflattened=array(X_train)
ytrain_unflattened=array(y)
xtest_unflattened=array(xtest)
ytest_unflattened=array(ytest)
#for i in range(len(ytrain_unflattened)):
#  ytrain=float(ytrain_unflattened[i])
#for j in range(len(Y_test)):
#  ytest_unflattened[i]=float(Y_test[i])
#print("x_unflattened",x_unflattened.shape,"\n")
#y_unflattened=array(Y_train)
#print(type(y_unflattened[0]))
#print("ytrain_unflattened",y_unflattened.shape,"\n")
#print("x_unflattened",x_unflattened.shape)
print("X_train shape",xtrain_unflattened.shape)
print("Y_train shape",ytrain_unflattened.shape)
#print("Y_train type",type(ytrain))

Y_train 
 [2, 3, 0, 0, 0, 4, 4, 0, 2, 0, 0, 0, 0, 5, 2, 0, 0, 3, 0, 5, 3, 0, 0, 3, 3, 0, 0, 0, 0, 4, 5, 0, 2, 3, 0, 0, 4, 0, 0, 3, 0, 0, 5, 2, 3, 0, 0, 2, 0, 3, 0, 0, 0, 5, 1, 3, 0, 0, 4, 2, 3, 1, 0, 0, 3, 1, 0, 4, 5, 3, 1, 4, 0, 1, 3, 1, 2, 5, 1, 0, 2, 2, 0, 0, 0, 1, 1, 2, 0, 5, 1, 0, 3, 0, 4, 0, 1, 2, 1, 0, 0, 0, 0, 1, 5, 0, 1, 4, 2, 2, 0, 0, 0, 4, 5, 2, 1, 5, 1, 0, 2, 4, 1, 1, 1, 3, 4, 5, 4, 2, 2, 0, 5, 0, 0, 2, 1, 4, 2, 0, 0, 1, 1, 3, 4, 0, 5, 3, 0, 3, 5, 4, 3, 0, 5, 1, 3, 4, 4, 0, 1, 2, 3, 5, 0, 2, 1, 3, 0, 1, 0, 0, 3, 0, 5, 0, 0, 3, 0, 1, 0, 5, 5, 0, 0, 0, 1, 0, 4, 0, 5, 0, 0, 4, 0, 0, 0, 0, 5, 4, 2, 0, 0, 3, 0, 1, 0, 4, 4, 4, 5, 3, 0, 5, 4, 0, 0, 0, 4, 0, 0, 5, 0, 0, 4, 0, 3, 0, 2, 5, 0, 5, 0, 0, 2, 0, 0, 0, 2, 0, 3, 0, 4, 5, 0, 0, 0, 0, 4, 3, 3, 0, 0, 3, 2, 4, 0, 2, 4, 0, 0, 3, 3, 2, 5, 1, 0, 5, 5, 4, 3, 0, 5, 2, 1, 2, 1, 3, 2, 0, 0, 5, 4, 1, 4, 3, 2, 3, 1, 0, 3, 0, 2, 5, 5, 3, 3, 0, 0, 0, 5, 0, 0, 0, 1, 0, 0, 3, 0, 5, 0, 0, 0, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 5, 1, 5, 2, 0, 0, 0,

# **Upsampling train only**

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
import pandas as pd
import numpy as np

X_train, X_test, Y_train, Y_test = train_test_split(Images, Labels, test_size=0.2)
print("X_train",len(X_train))
print("X_test ",len(X_test))
print("Y_train ",len(Y_train))
#print("Y_train \n",Y_train,"\n")
#print("Y_test \n",Y_test,"\n")
y=[]
for i in range(0,len(Y_train)):
  y.append(Y_train[i])

print("1    ",y.count(1))  
print("2    ",y.count(2)) 
print("3    ",y.count(3)) 
print("4    ",y.count(4)) 
print("5    ",y.count(5)) 
ymax = max(y.count(1),y.count(2),y.count(3),y.count(4),y.count(5))
print("MAX N0 IN Y- LABELS ",ymax)


X_train 501
X_test  126
Y_train  501
1     17
2     31
3     5
4     89
5     46
MAX N0 IN Y- LABELS  89
X_train of %d   0 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]] Y_train of %d    0
X_train of %d   1 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]] Y_train of %d    1
X_train of %d   2 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]] Y_train of %d    2
X_train of %d   3 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]] Y_train of %d    3
X_train of %d   4 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]] Y_train of %d    4
X_train of %d   5 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ...

In [33]:
image0=[]
image1=[]
image2=[]
image3=[]
image4=[]
image5=[]
for i in range(0,len(Y_train)):
  if(Y_train[i]==0):
    image0.append(X_train[i])
  elif(Y_train[i]==1):
    image1.append(X_train[i])
  elif(Y_train[i]==2):
    image2.append(X_train[i])
  elif(Y_train[i]==3):
    image3.append(X_train[i])
  elif(Y_train[i]==4):
    image4.append(X_train[i])
  elif(Y_train[i]==5):
    image5.append(X_train[i])
print("length of 0",len(image0))
print("length of 1",len(image1))
print("length of 2",len(image2))
print("length of 3",len(image3))
print("length of 4",len(image4))
print("length of 5",len(image5))

length of 0 313
length of 1 17
length of 2 31
length of 3 5
length of 4 89
length of 5 46


In [35]:
df_minority_upsampled_a = resample(image1,replace=True,n_samples=ymax-y.count(1),random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_a = np.vstack([image1, df_minority_upsampled_a])

df_minority_upsampled_b = resample(image2,replace=True,n_samples=ymax-y.count(2),random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_b = np.vstack([image2, df_minority_upsampled_b])

df_minority_upsampled_f = resample(image3,replace=True,n_samples=ymax-y.count(3),random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_f = np.vstack([image3, df_minority_upsampled_f])

df_minority_upsampled_v = resample(image5,replace=True,n_samples=ymax-y.count(5),random_state=123)
 
# Combine majority class with upsampled minority class
df_upsampled_v = np.vstack([image5, df_minority_upsampled_v])


# Display new class counts
#df_upsampled_v.balance.value_counts()
#print(type(df_minority_upsampled_v))

#print(df_upsampled_v)
print(type(df_minority_upsampled_a))
print("a upsampled",len(df_upsampled_a))
print(len(df_minority_upsampled_a))
print(len(imagea))
#print(df_upsampled_a)
print(type(df_minority_upsampled_b))
print("b upsampled",len(df_upsampled_b))
print(len(df_minority_upsampled_b))
print(len(imageb))
print(type(df_minority_upsampled_f))
print("f upsampled",len(df_upsampled_f))
print(len(df_minority_upsampled_f))
print(len(imagef))
print("v upsampled",len(df_upsampled_v))
print(len(df_minority_upsampled_v))
print(len(imagev))

<class 'list'>
a upsampled 89
72
17
<class 'list'>
b upsampled 89
58
39
<class 'list'>
f upsampled 89
84
6
v upsampled 89
43
61


In [36]:
#preparing x train and y train for svm and ann
x_train=[]
for i in range(len(X_train)):
  x_train.append(X_train[i].flatten())
print("len x_train",len(x_train),"\n")


x_test=[]
for i in range(len(X_test)):
  x_test.append(X_test[i].flatten())
print("len x_test",len(x_test),"\n")

x=np.asarray(x_train)
#print(x.shape[1:])
y=np.asarray(Y_train)
xtest=np.asarray(x_test)
ytest=np.asarray(Y_test)
#print(len(y))

#preparing x train and y train for cnn

xtrain_unflattened=array(X_train)
ytrain_unflattened=array(y)
xtest_unflattened=array(xtest)
ytest_unflattened=array(ytest)
print("X_train shape",xtrain_unflattened.shape)
print("Y_train shape",ytrain_unflattened.shape)
#print("Y_train type",type(ytrain))

len x_train 501 

len x_test 126 

X_train shape (501, 100, 100)
Y_train shape (501,)


In [0]:
node = tf.constant(6.0) 
print(node)

Tensor("Const_5:0", shape=(), dtype=float32)


In [0]:
from sklearn import svm
from sklearn.metrics import accuracy_score
gammas = [0.1, 1, 10, 100]
kernels = ['linear', 'rbf', 'poly']
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
for g in gammas:
  for k in kernels:
    svc = svm.SVC(kernel=k,gamma=g).fit(x, y)    
    predicted = svc.predict(xtest)  
    results = confusion_matrix(ytest, predicted)
    print ('Confusion Matrix :')
    print(results)
    print ('Accuracy Score :',accuracy_score(ytest, predicted))
    print ('Report : ')
    print (classification_report(ytest, predicted))
    print(results)

Confusion Matrix :
[[77  1  1  1  0  1]
 [ 0  4  0  0  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  1  0  0]
 [ 4  0  0  0 17  0]
 [ 0  0  0  0  0 10]]
Accuracy Score : 0.9365079365079365
Report : 
              precision    recall  f1-score   support

           0       0.95      0.95      0.95        81
           1       0.80      1.00      0.89         4
           2       0.90      1.00      0.95         9
           3       0.50      1.00      0.67         1
           4       1.00      0.81      0.89        21
           5       0.91      1.00      0.95        10

   micro avg       0.94      0.94      0.94       126
   macro avg       0.84      0.96      0.88       126
weighted avg       0.94      0.94      0.94       126

[[77  1  1  1  0  1]
 [ 0  4  0  0  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  1  0  0]
 [ 4  0  0  0 17  0]
 [ 0  0  0  0  0 10]]
Confusion Matrix :
[[79  1  0  1  0  0]
 [ 0  4  0  0  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  1  0  0]
 [ 6  0  0  0 15  0]
 [ 0  0  0  0 

In [0]:
#kernels = [‘linear’, ‘rbf’, ‘poly’]
#
#for kernel in kernels:
#  svc = svm.SVC(kernel=kernel).fit(x, y)
#  plotSVC(‘kernel=’ + str(kernel))

In [0]:
#degrees = [0, 1, 2, 3, 4, 5, 6]
#
#for degree in degrees:
#  svc = svm.SVC(kernel=’poly’, degree=degree).fit(X, y)
#  plotSVC(‘degree=’ + str(degree))

In [0]:
data_train = datagen.flow(x=X_train, y=Y_train, batch_size=32, shuffle=True)
data_val = datagen.flow(x=X_train, y=Y_train, batch_size=32, shuffle=True)
#
#from sklearn.model_selection import train_test_split
#
#val_split = 0.25
#XV_train, X_val, YV_train, Y_val = train_test_split(X_train, Y_train, test_size=val_split, shuffle = True)
#
print(len(data_train))
print(len(data_val))


16
16


(10000,)
501


In [0]:
model = create_model()
from sklearn import svm
#clf=svm.SVC(gamma=0.001,C=100)
#clf.fit(x,y)
#data = (x_train ,Y_train)
#model.fit_generator((x_train ,Y_train), epochs = 10,steps_per_epoch=1 )#validation_data=(x_val,Y_val))
#data_train = datagen.flow(x=X_train, y=Y_train, batch_size=32, shuffle=True)
    
results = model.fit_generator(data_train,steps_per_epoch=data_train.n/32 ,verbose=1,epochs=1)#validation_data=data_val) 
#model.fit(X_train,Y_train)

In [0]:
#define a function to fit the model
def fit_and_evaluate(datagen,model,X_train,Y_train ,X_val,Y_val , EPOCHS ,X_test,Y_test):
    
    data_train = datagen.flow(x=X_train, y=Y_train, batch_size=32, shuffle=True)
    
    results = model.fit_generator(
        data_train,
        steps_per_epoch=data_train.n/32 ,verbose=1,
    epochs=EPOCHS,validation_data=(X_val,Y_val)) 
    
    score = model.evaluate(x=X_test, y=Y_test)
    print('Test loss:', score[0])
    print('Test accuracy:', score[1]) 
    y_pred =np.round( model.predict(X_test))

    print(confusion_matrix(Y_test,y_pred))   
    print(accuracy_score(Y_test, y_pred))
    return results

In [0]:
skf = StratifiedKFold(n_splits=10, shuffle=True)
model_history = [] 
i=0
for train_idx, val_idx in skf.split(X_train, Y_train):
  print( "Running Fold", i+1, "/10")
  model_history.append(fit_and_evaluate(datagen,model,X_train[train_idx], Y_train[train_idx],X_train[val_idx], Y_train[val_idx], 10,X_test,Y_test))
  i+=1
  print("======="*12, end="\n\n\n")

In [0]:
def load_path():
    root_path = '/content/drive/My Drive/collab/grad/dataset'
    Images =[]
    labels=[]
 
    for subdir, dirs, files in (os.walk(root_path)):
        for filename in files:
            
            path = os.path.join(subdir,filename)
            image = cv2.imread(path)
            #plt.imshow(image),plt.show()
            #print(path)
            image =cv2.resize(image, (100, 100))
            image=cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            image = np.expand_dims(image, axis=2)
            image = image.astype('float32')
            image /=255.0
            Images.append(image)            
            #if subdir.split('_')[-1]=='OpenedFace' | subdir.split('_')[-1]=='AugmentedOpen':
            if subdir.split('_')[-1]=='OpenedFace':
                labels.append(1)
            else :
                labels.append(0)
            
            
    return Images,labels  

In [0]:
#Hadeer's model
from keras.layers.advanced_activations import LeakyReLU

def create_model():
  
  
  model = Sequential()

  model.add(Conv2D(32, kernel_size=(3, 3),activation='linear',input_shape=(100,100,1),padding='same'))
  model.add(LeakyReLU(alpha=0.1))
  model.add(MaxPooling2D((2, 2),padding='same'))
  
  model.add(Conv2D(64, (3, 3), activation='linear',padding='same'))
  model.add(LeakyReLU(alpha=0.1))
  model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
  
  
  model.add(Conv2D(64, (3, 3), activation='linear',padding='same'))
  model.add(LeakyReLU(alpha=0.1))
  model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
  
  model.add(Conv2D(128, (3, 3), activation='linear',padding='same'))
  model.add(LeakyReLU(alpha=0.1))                  
  model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
  

  model.add(Conv2D(128, (3, 3), activation='linear',padding='same'))
  model.add(LeakyReLU(alpha=0.1))                  
  model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
  
  
  
  
  model.add(Flatten())
  model.add(Dense(128, activation='linear'))
  model.add(LeakyReLU(alpha=0.1))                  
  model.add(Dense(1, activation='softmax'))
  

  return model


#fashion_train = fashion_model.fit(x_train, y_train, batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(x_valid, y_valid))
#
#test_eval = fashion_model.evaluate(x_test, y_test, verbose=0)


In [0]:
model = create_model()
model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adam(),metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=32,epochs=10,verbose=1,validation_data=(X_test, Y_test))

In [0]:
#fatma's model
from keras.utils import to_categorical
height = 100
width = 100
dims = 1
def create_model():
    """
        Create model
        :return:
    """
    #model = Sequential()
    #model.add(Dense(100, input_dim=100, activation='relu'))
    #model.add(Dense(8, activation='softmax'))
    #model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model = Sequential()

    model.add(Conv2D(32, (3,3), padding = 'same' ,input_shape=(height,width,dims)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
  
    model.add(Conv2D(64, (2,2), padding= 'same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    
    model.add(Conv2D(128, (2,2), padding='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dense(1))
    model.add(Activation('sigmoid'))

    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])


    return model